Apple old page
ositaadimma/Apple-old-page pull request #1
Opened 2020-07-29 19:45 UTC by BrianSammit

2020-07-29 21:13 UTC, expjazz requested changes
## Status: Changes required :recycle: 

#### You did great work on this page. It looks splendid :clap: 

However, there are still minor details in order to check the minimum requirements (check them in the inline comments below).

#### General comments:
- Do not commit the node modules folder. You should use the .gitignore to hide it from git.
![image](https://user-images.githubusercontent.com/61479648/88853954-ec839e80-d1c6-11ea-9ddc-04f0a3ca5f16.png)
- You have Linter Errors

Like I said above, the design is great and the code is very clean and easy to understand :ok_hand: 

### Please make the required changes and resubmit for a new code review once you are ready
Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-07-29 21:13 UTC, expjazz commented on index.html
> +    </div>
- [ ] These images should be links as is in the original.

2020-07-29 21:13 UTC, expjazz commented on index.html
> +          <li><img class="img-footer" src="/images/icone.png" alt="" /></li>
- [ ] They also need to be a link

2020-07-29 21:13 UTC, expjazz commented on index.html
> +    <section class="main">
- [ ] You are missing an icon here

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/88853344-f48f0e80-d1c5-11ea-9464-8933cff27dfa.png) | ![image](https://user-images.githubusercontent.com/61479648/88853420-14becd80-d1c6-11ea-8a3d-1c7553505653.png)|

- [ ] Also make them link as is in the original

2020-07-30 00:09 UTC, bertil291utn commented
**Status:** Changes requested 🟠  :shipit:? Not yet.

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### Your work is amazing you master it GitHub Flow you have a professional README file. 

However, in order to accomplish as the actual page, you required to do these changes, listed below:
### General requirements 
- [ ] Add `node_modules` directory  to `.gitignore` file
- [ ] Remove or add to gitignore `.vscode` directory
- [ ] Add link demo to link de mo section with markdown syntax `[link-demo](https://your-link)`
![image](https://user-images.githubusercontent.com/24902525/88862894-07eea980-d1c7-11ea-9317-d85c1c284178.png)

### Specific requirements
- Hero section
- [ ] Use `repeat:none;` property to don't repeat your hero background image
![image](https://user-images.githubusercontent.com/24902525/88863218-ee019680-d1c7-11ea-9dc5-00c5a7d6a609.png)
- Footer
- [ ] Remove extra space 
![image](https://user-images.githubusercontent.com/24902525/88863609-dd055500-d1c8-11ea-8859-bc84fca50a3d.png)

- Bottom

- [ ] Each image should overlap each other

| ACTUAL WEB PAGE | YOURS |
| :-------------: | :---: |
| ![image](https://user-images.githubusercontent.com/24902525/88865616-fe1c7480-d1cd-11ea-82ba-53d506a1f0f2.png) | ![image](https://user-images.githubusercontent.com/24902525/88865575-e0e7a600-d1cd-11ea-8297-a79447df0202.png) |
### Improvements for next projects

- [ ] Write a pull request message in the PR box, according to this [example](https://cdn.filestackcontent.com/osvFJEkQHWQsgDe0PJoQ)

![image](https://user-images.githubusercontent.com/24902525/88863020-58660700-d1c7-11ea-98a1-7be0bf633e95.png)

### Summary

- Please add the node_modules directory to .gitignore file 
- Don't forget to work with inline comments below this comment box.

<hr>

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-07-30 10:53 UTC, kitpao requested changes
# 👋 Hello @BrianSammit  and @ositaadimma 

You did a nice job and are almost there, please just make the missing changes required by previous TSE and you will be good to go 👍 

- [x] **[MANDATORY]** I see you added the node_modules folder to your .gitignore as requested, but for it to work, you should follow the next steps:
  * In your local, copy the node_modules folder and put it somewhere else outside your repo
  * Delete the node_modules folder from repo
  * commit and push your changes
  * Then, you can return the copied folder to your repo and it will be ignored by git

- [x] .vscode directory should also be added to gitignore

- [ ] Add a pull request message with a short summary of the changes you introduced in this branch, like in the example:
![image](https://user-images.githubusercontent.com/53256139/88913714-1e2c5200-d227-11ea-86b8-c57297465ea3.png)

### ♻️ Status: Your project requires some additional changes ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-07-30 10:53 UTC, kitpao commented on README.md
> +[Live Demo Link](https://rawcdn.githack.com/ositaadimma/Apple-old-page/cc02d9056e7458404f51957be3764b8e976734fc/index.html)
- [ ] **[OPTIONAL]** As a suggestion, so you don't have to be manually updating this link during your code reviews, use the second link (development link) in githack, that one will automatically load your last version in the same branch :)

2020-07-30 10:53 UTC, kitpao commented on css/styles.css
> +}
- [ ] Your images are stretched, you can add `object-fit: cover;` rule to make them keep their original proportions

2020-07-30 10:53 UTC, kitpao commented on index.html
> +        </p>
- [ ] Please add an anchor tag `<a>`  to your headers as required by previous TSE, it is not enough to use cursor: pointer;

2020-07-30 10:53 UTC, kitpao commented on css/styles.css
> +  background-size: 100%;
- [ ] You did great implementing the background-repeat: no-repeat, but now you have a blank space between the hero image and the bottom part, to fix it, use the 'cover' size on the background image
![image](https://user-images.githubusercontent.com/53256139/88914635-8596d180-d228-11ea-9da5-0aecbed53d2f.png)

2020-07-30 13:44 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello @ositaadimma @BrianSammit** 
Good job with your new submission for this project :muscle:  :muscle:
There are some improvements to do before you can go ahead:
- [ ] your footer doesn't have the USA flag icon
- [ ] Don't overuse ID Selectors
- [ ] use gradient for the navbar.
- [ ] your linter highlights some errors
- [ ]  Your live demo looks like this:

![](https://i.imgur.com/WGFrHTHl.png)

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-07-30 13:44 UTC, andresporras3423 commented on css/styles.css
> +  background-image: url(../img/nav-bar-image.png);
Don't use an image, use a gradient for the background of the navbar.

2020-07-30 13:44 UTC, andresporras3423 commented on css/styles.css
> +#body-text-p2 a {
Don't overuse ID selectors

2020-07-30 14:53 UTC, bertil291utn requested changes
**Status:** Changes requested 🟠  :shipit:? Not yet.

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### Your work is amazing you master it GitHub Flow you have a professional README file. 

However, in order to follow CSS best practices you required to do these changes, listed inline comments:

### Optional
- [ ] Use the [`<main>` tag](https://www.w3schools.com/tags/tag_main.asp) for the dominant content of the `<body>` of a document

### Summary

-  Don't forget to work with inline comments below this comment box.

<hr>

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-07-30 14:53 UTC, bertil291utn commented on css/styles.css
> +  background: linear-gradient(rgb(116, 116, 116) 50%, rgb(107, 107, 107) 50%);
## Using the Same Rule Repetitively[1]
- [ ] Create a class once and the use in each HTML tag where you need it.
- [ ] Delete all your `display:flex;` properties in entire CSS file
- [ ] Add your HTML tags

**Example:**

**CSS file**

```
.flex{
  display: flex;
}
```
**Html file**

```
<div class="flex">
```
**Note:** Do this change to all properties in this file 

<hr>

_[1] [Good and bad  CSS practices](https://speckyboy.com/good-bad-css-practices/)_

2020-07-30 14:53 UTC, bertil291utn commented on css/styles.css
> +  right: 50px;
## Using the Same Rule Repetitively[1]
- [ ] Create a class once and the use in each HTML tag where you need it.
- [ ] Delete all your `color: white;` properties in entire CSS file
- [ ] Add your HTML tags

**Example:**

**CSS file**

```
.color-white{
  color: white;
}
```
**Html file**

```
<div class="color-white">
```
**Note:** Do this change to all properties in this file 

<hr>

_[1] [Good and bad  CSS practices](https://speckyboy.com/good-bad-css-practices/)_

2020-07-30 18:02 UTC, kitpao requested changes
# 👋 Hello Team,

Nice work! you only have 4 mandatory changes pending from previous TSEs. Kindly read them below 🔽 

- [ ] You are still missing the pull request message with a short summary of the changes you introduced in this branch, just edit your pull request.

### ♻️ Status: Your project requires some additional changes ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-07-30 18:02 UTC, kitpao commented on index.html
> +        ipad in their unique ways to add to the world's story. <br />
- [ ] You are still missing an anchor tag `<a>` for this text

2020-07-30 18:02 UTC, kitpao commented on css/styles.css
> +}
- [ ] You are repeating `display: flex;` in lines 57, 92 and 98 in this file for .ul-1 a, .thumbnails a, and .thumbnails img. The objective of doing this special class .flex is that you don't repeat the same rule, to solve this, just go to the HTML elements you are referring to and add the class "flex"

2020-07-30 19:26 UTC, BrianSammit commented
This pull request is to add an old Apple page to the master branch, we made this Apple page with background image, a navbar with background: linear-gradient property and using special class .flex and color .color-white.

2020-07-30 19:39 UTC, tirthajyoti-ghosh approved these changes
# Approved ✅

## You have done an incredible job making this project 👏🧨💪! Just perfect 💯! 

### You have met all the requirements of the project. Go ahead and merge it! Onto the next project 🚀 !

Happy coding 👨‍💻 

<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

2020-07-30 20:07 UTC, merged